import type {Component} from 'vue'
import {ControlLayout} from '~/types'
import {
    BreakoutGame,
    CentipedeGame,
    CheckersGame,
    ColorSurge,
    ConnectFour,
    CosmicMinesweeper,
    CosmicPong,
    DicePursuit,
    FlappyRocket,
    FlowConnect,
    FroggerGame,
    Game2048,
    GomokuGame,
    GravityFlip,
    LaserBounce,
    LightsOut,
    MemoryMatch,
    MeteorCatcher,
    MissileCommand,
    NeonTetris,
    NeonWhack,
    NonogramGame,
    OrbitShield,
    PacMan,
    PianoTiles,
    SimonSays,
    SlidePuzzle,
    SnakeGame,
    SokobanGame,
    SpaceInvaders,
    SudokuGame,
    TypeAttack,
    WordleGame,
    WordSearch,
    AnagramBlitz,
    MastermindGame,
    // New games
    ReversiGame,
    BattleshipGame,
    MatchThree,
    TowerDefense,
    PinballGame,
    BlackjackGame,
    SolitaireGame,
    PipesPuzzle,
    TowerHanoi,
    BoggleGame,
    BilliardsGame,
    TriviaQuiz,
    ColorFlood,
    PlatformerGame,
} from '#components'

export enum GameSlug {
    SpaceInvaders  = 'space-invaders',
    FlappyRocket   = 'flappy-rocket',
    CosmicBreakout = 'cosmic-breakout',
    NeonSnake      = 'neon-snake',
    Game2048       = '2048',
    PlanetMemory   = 'planet-memory',
    NeonTetris     = 'neon-tetris',
    CosmicPong     = 'cosmic-pong',
    MeteorCatcher  = 'meteor-catcher',
    GravityFlip    = 'gravity-flip',
    OrbitShield    = 'orbit-shield',
    CosmicMinesweeper = 'cosmic-minesweeper',
    TypeAttack     = 'type-attack',
    NeonWhack      = 'neon-whack',
    LaserBounce    = 'laser-bounce',
    ColorSurge     = 'color-surge',
    // Puzzle games
    Sudoku         = 'sudoku',
    Nonogram       = 'nonogram',
    Sokoban        = 'sokoban',
    SlidePuzzle    = 'slide-puzzle',
    Mastermind     = 'mastermind',
    LightsOut      = 'lights-out',
    FlowConnect    = 'flow-connect',
    Gomoku         = 'gomoku',
    // Word games
    Wordle         = 'wordle',
    WordSearch     = 'word-search',
    AnagramBlitz   = 'anagram-blitz',
    // Classic games
    PacMan         = 'pac-man',
    Frogger        = 'frogger',
    MissileCommand = 'missile-command',
    Centipede      = 'centipede',
    SimonSays      = 'simon-says',
    Checkers       = 'checkers',
    PianoTiles     = 'piano-tiles',
    ConnectFour    = 'connect-four',
    DicePursuit    = 'dice-pursuit',
    // New unique games
    Reversi        = 'reversi',
    Battleship     = 'battleship',
    MatchThree     = 'match-three',
    TowerDefense   = 'tower-defense',
    Pinball        = 'pinball',
    Blackjack      = 'blackjack',
    Solitaire      = 'solitaire',
    Pipes          = 'pipes',
    TowerOfHanoi   = 'tower-of-hanoi',
    Boggle         = 'boggle',
    Billiards      = 'billiards',
    Trivia         = 'trivia',
    ColorFlood     = 'color-flood',
    Platformer     = 'platformer',
}

export enum GameGenre {
    ARCADE   = 'ARCADE',
    SURVIVAL = 'SURVIVAL',
    ONE_TAP  = 'ONE-TAP',
    CLASSIC  = 'CLASSIC',
    PUZZLE   = 'PUZZLE',
    CASUAL   = 'CASUAL',
    WORD     = 'WORD',
}

export enum GameColor {
    NEON_BLUE = 'neon-blue',
    NEON_EMERALD = 'neon-emerald',
    NEON_PURPLE = 'neon-purple',
    NEON_PINK = 'neon-pink',
}

export interface GameEntry {
    slug: GameSlug
    id: string
    name: string
    desc: string
    genre: string
    color: GameColor
    component: Component
    controls: ControlLayout
}

export const games: GameEntry[] = [
    {
        slug: GameSlug.SpaceInvaders,
        id: 'SpaceInvaders',
        name: 'Space Invaders',
        desc: 'Shoot down the alien fleet before they reach Earth. Classic arcade action.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_BLUE,
        component: SpaceInvaders,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.FlappyRocket,
        id: 'FlappyRocket',
        name: 'Flappy Rocket',
        desc: "Boost your rocket through narrow gaps. One tap to fly — don't crash.",
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: FlappyRocket,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.CosmicBreakout,
        id: 'BreakoutGame',
        name: 'Cosmic Breakout',
        desc: 'Break every neon brick with a bouncing energy ball. Classic and satisfying.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: BreakoutGame,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.NeonSnake,
        id: 'SnakeGame',
        name: 'Neon Snake',
        desc: "Eat the glowing orbs and grow without hitting yourself. Speed builds up.",
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_EMERALD,
        component: SnakeGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.Game2048,
        id: 'Game2048',
        name: '2048',
        desc: 'Slide and merge tiles to reach 2048. Deceptively simple, endlessly deep.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: Game2048,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.PlanetMemory,
        id: 'MemoryMatch',
        name: 'Planet Memory',
        desc: 'Match all 8 planet pairs in the fewest flips. Test your space memory.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: MemoryMatch,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonTetris,
        id: 'NeonTetris',
        name: 'Neon Tetris',
        desc: 'Stack neon tetrominoes and clear lines before the stack reaches the top.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: NeonTetris,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.CosmicPong,
        id: 'CosmicPong',
        name: 'Cosmic Pong',
        desc: 'Face the CPU in a neon pong duel. First to 7 wins. Speed up or lose.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: CosmicPong,
        controls: ControlLayout.UpDown,
    },
    {
        slug: GameSlug.MeteorCatcher,
        id: 'MeteorCatcher',
        name: 'Meteor Catcher',
        desc: 'Move your ship to catch falling meteors. Avoid the bombs — 3 lives.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_EMERALD,
        component: MeteorCatcher,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.GravityFlip,
        id: 'GravityFlip',
        name: 'Gravity Flip',
        desc: 'Flip gravity to navigate a shifting sine-wave tunnel — how far can you go?',
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: GravityFlip,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.OrbitShield,
        id: 'OrbitShield',
        name: 'Orbit Shield',
        desc: 'Rotate a neon arc shield to deflect incoming meteors and protect your planet.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_EMERALD,
        component: OrbitShield,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.CosmicMinesweeper,
        id: 'CosmicMinesweeper',
        name: 'Cosmic Minesweeper',
        desc: 'Sweep a 9×9 minefield in deep space. Reveal cells, flag mines — clear without detonating.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: CosmicMinesweeper,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.TypeAttack,
        id: 'TypeAttack',
        name: 'Type Attack',
        desc: 'Space words fall from above — type them before they reach the danger line.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: TypeAttack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonWhack,
        id: 'NeonWhack',
        name: 'Neon Whack',
        desc: 'Whack glowing alien heads as they pop out of space-station ports. Click fast.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_EMERALD,
        component: NeonWhack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.LaserBounce,
        id: 'LaserBounce',
        name: 'Laser Bounce',
        desc: 'Ricochet laser shots off walls to destroy neon targets before shots run out.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: LaserBounce,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.ColorSurge,
        id: 'ColorSurge',
        name: 'Color Surge',
        desc: 'Shoot colored bubbles into the grid and pop matching clusters before they reach the danger line.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: ColorSurge,
        controls: ControlLayout.LrFire,
    },
    // ── Puzzle ────────────────────────────────────────────────────────────────
    {
        slug: GameSlug.Sudoku,
        id: 'SudokuGame',
        name: 'Sudoku',
        desc: 'Fill every row, column and 3×3 box with digits 1–9. Three difficulty levels.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: SudokuGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Nonogram,
        id: 'NonogramGame',
        name: 'Nonogram',
        desc: 'Decode pixel art hidden inside an 8×8 grid using number clues on each row and column.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: NonogramGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Sokoban,
        id: 'SokobanGame',
        name: 'Sokoban',
        desc: 'Push every crate onto the glowing goal squares across 5 hand-crafted warehouse levels.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_EMERALD,
        component: SokobanGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.SlidePuzzle,
        id: 'SlidePuzzle',
        name: 'Slide Puzzle',
        desc: 'Slide the 15 numbered tiles into order. Click tiles adjacent to the blank to move them.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: SlidePuzzle,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Mastermind,
        id: 'MastermindGame',
        name: 'Mastermind',
        desc: 'Crack the hidden 4-color code in 10 attempts. Black pegs = right position.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: MastermindGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.LightsOut,
        id: 'LightsOut',
        name: 'Lights Out',
        desc: 'Click cells to toggle them and their four neighbors. Turn every light off.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: LightsOut,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.FlowConnect,
        id: 'FlowConnect',
        name: 'Flow Connect',
        desc: 'Draw paths to connect each pair of colored dots. Fill every cell without crossing.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: FlowConnect,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Gomoku,
        id: 'GomokuGame',
        name: 'Gomoku',
        desc: 'Place stones on a 15×15 board. Get five in a row to win against the CPU.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_EMERALD,
        component: GomokuGame,
        controls: ControlLayout.None,
    },
    // ── Word ──────────────────────────────────────────────────────────────────
    {
        slug: GameSlug.Wordle,
        id: 'WordleGame',
        name: 'Wordle',
        desc: 'Guess the secret 5-letter word in 6 tries. Green = correct spot, yellow = wrong position.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_EMERALD,
        component: WordleGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.WordSearch,
        id: 'WordSearch',
        name: 'Word Search',
        desc: 'Hunt for 8 hidden space words in a 10×10 letter grid. Drag to highlight.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_BLUE,
        component: WordSearch,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.AnagramBlitz,
        id: 'AnagramBlitz',
        name: 'Anagram Blitz',
        desc: 'Unscramble as many words as you can in 60 seconds. +10 per correct, -1 to skip.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_PINK,
        component: AnagramBlitz,
        controls: ControlLayout.None,
    },
    // ── Classic ───────────────────────────────────────────────────────────────
    {
        slug: GameSlug.PacMan,
        id: 'PacMan',
        name: 'Pac-Man',
        desc: 'Eat all the dots while avoiding ghosts. Grab a power pellet to turn the tables.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: PacMan,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.Frogger,
        id: 'FroggerGame',
        name: 'Frogger',
        desc: 'Guide your frog safely across busy roads and a fast-moving river.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_EMERALD,
        component: FroggerGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.MissileCommand,
        id: 'MissileCommand',
        name: 'Missile Command',
        desc: 'Click to launch interceptors and destroy incoming missiles before they hit your cities.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: MissileCommand,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Centipede,
        id: 'CentipedeGame',
        name: 'Centipede',
        desc: 'Blast the descending centipede before it reaches you. Beware wandering spiders.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: CentipedeGame,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.SimonSays,
        id: 'SimonSays',
        name: 'Simon Says',
        desc: 'Watch the color sequence flash, then repeat it. One mistake and it is game over.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_EMERALD,
        component: SimonSays,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Checkers,
        id: 'CheckersGame',
        name: 'Checkers',
        desc: 'Classic draughts against a minimax AI. Capture all opponent pieces or block every move.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: CheckersGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.PianoTiles,
        id: 'PianoTiles',
        name: 'Piano Tiles',
        desc: 'Click the falling pink tiles before they pass the line. Miss three and the music stops.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: PianoTiles,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.ConnectFour,
        id: 'ConnectFour',
        name: 'Connect Four',
        desc: 'Drop discs to get four in a row against a minimax CPU. Horizontal, vertical or diagonal.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_PURPLE,
        component: ConnectFour,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.DicePursuit,
        id: 'DicePursuit',
        name: 'Dice Pursuit',
        desc: 'Roll 5 dice up to 3 times per turn and score across 13 Yahtzee-style categories.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PURPLE,
        component: DicePursuit,
        controls: ControlLayout.None,
    },
    // ── 14 New Unique Games ───────────────────────────────────────────────────
    {
        slug: GameSlug.Reversi,
        id: 'ReversiGame',
        name: 'Reversi',
        desc: 'Outflank your opponent to flip their discs. Control the most squares when the board is full.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: ReversiGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Battleship,
        id: 'BattleshipGame',
        name: 'Battleship',
        desc: 'Place your fleet and hunt the enemy ships. Call your shots — sink all 5 to win.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_EMERALD,
        component: BattleshipGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.MatchThree,
        id: 'MatchThree',
        name: 'Match Three',
        desc: 'Swap adjacent gems to line up three or more. Chain combos and clear the board.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: MatchThree,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.TowerDefense,
        id: 'TowerDefense',
        name: 'Tower Defense',
        desc: 'Place turrets to stop enemy waves from crossing your base. Spend kills to build more.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: TowerDefense,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Pinball,
        id: 'PinballGame',
        name: 'Pinball',
        desc: 'Launch the ball, smash bumpers, and keep it in play with the flippers. Reach 5000 pts.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_BLUE,
        component: PinballGame,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.Blackjack,
        id: 'BlackjackGame',
        name: 'Blackjack',
        desc: 'Beat the dealer to 21 without busting. Hit, stand, or double down over 5 rounds.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_EMERALD,
        component: BlackjackGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Solitaire,
        id: 'SolitaireGame',
        name: 'Solitaire',
        desc: 'Classic Klondike card solitaire. Stack cards, build foundations, clear the tableau.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PURPLE,
        component: SolitaireGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Pipes,
        id: 'PipesPuzzle',
        name: 'Pipes',
        desc: 'Rotate pipe tiles to create a connected flow from source to sink. No leaks allowed.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: PipesPuzzle,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.TowerOfHanoi,
        id: 'TowerHanoi',
        name: 'Tower of Hanoi',
        desc: 'Move all rings from the left peg to the right. Never place a larger ring on a smaller.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: TowerHanoi,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Boggle,
        id: 'BoggleGame',
        name: 'Boggle',
        desc: 'Trace adjacent letters to form words in 90 seconds. Longer words score more.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_EMERALD,
        component: BoggleGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Billiards,
        id: 'BilliardsGame',
        name: 'Billiards',
        desc: 'Aim the cue, set power, and pot your balls before the CPU clears the table.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: BilliardsGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Trivia,
        id: 'TriviaQuiz',
        name: 'Trivia Quiz',
        desc: '10 questions across space, science and culture. Answer fast for bonus points.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: TriviaQuiz,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.ColorFlood,
        id: 'ColorFlood',
        name: 'Color Flood',
        desc: 'Flood-fill from the corner — cover the whole board in one color within 25 moves.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: ColorFlood,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Platformer,
        id: 'PlatformerGame',
        name: 'Platformer',
        desc: 'Run and jump across platforms, collect coins, dodge enemies. Reach the flag.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_EMERALD,
        component: PlatformerGame,
        controls: ControlLayout.Dpad,
    },
]

export const useGames = () => {
    const getGameBySlug = (slug: string) => games.find(game => game.slug === slug) ?? null
    return {games, getGameBySlug}
}
