import type {Component} from 'vue'
import {ControlLayout} from '~/types'
import {
    AsteroidDodge,
    BreakoutGame,
    CentipedeGame,
    CheckersGame,
    ColorSurge,
    ConnectFour,
    CosmicMinesweeper,
    CosmicPong,
    DicePursuit,
    FlappyRocket,
    FlowConnect,
    FroggerGame,
    Game2048,
    GomokuGame,
    GravityFlip,
    LaserBounce,
    LightsOut,
    MemoryMatch,
    MeteorCatcher,
    MissileCommand,
    NeonRunner,
    NeonTetris,
    NeonWhack,
    NonogramGame,
    OrbitShield,
    PacMan,
    PianoTiles,
    SimonSays,
    SlidePuzzle,
    SnakeGame,
    SokobanGame,
    SpaceInvaders,
    StarCatcher,
    SudokuGame,
    TypeAttack,
    WarpTunnel,
    WordleGame,
    WordSearch,
    AnagramBlitz,
    MastermindGame,
} from '#components'

export enum GameSlug {
    SpaceInvaders  = 'space-invaders',
    AsteroidDodge  = 'asteroid-dodge',
    FlappyRocket   = 'flappy-rocket',
    CosmicBreakout = 'cosmic-breakout',
    NeonSnake      = 'neon-snake',
    Game2048       = '2048',
    PlanetMemory   = 'planet-memory',
    NeonTetris     = 'neon-tetris',
    CosmicPong     = 'cosmic-pong',
    MeteorCatcher  = 'meteor-catcher',
    NeonRunner     = 'neon-runner',
    GravityFlip    = 'gravity-flip',
    OrbitShield    = 'orbit-shield',
    StarCatcher    = 'star-catcher',
    CosmicMinesweeper = 'cosmic-minesweeper',
    TypeAttack     = 'type-attack',
    NeonWhack      = 'neon-whack',
    LaserBounce    = 'laser-bounce',
    WarpTunnel     = 'warp-tunnel',
    ColorSurge     = 'color-surge',
    // New games
    Sudoku         = 'sudoku',
    Nonogram       = 'nonogram',
    Sokoban        = 'sokoban',
    SlidePuzzle    = 'slide-puzzle',
    Mastermind     = 'mastermind',
    LightsOut      = 'lights-out',
    FlowConnect    = 'flow-connect',
    Gomoku         = 'gomoku',
    Wordle         = 'wordle',
    WordSearch     = 'word-search',
    AnagramBlitz   = 'anagram-blitz',
    PacMan         = 'pac-man',
    Frogger        = 'frogger',
    MissileCommand = 'missile-command',
    Centipede      = 'centipede',
    SimonSays      = 'simon-says',
    Checkers       = 'checkers',
    PianoTiles     = 'piano-tiles',
    ConnectFour    = 'connect-four',
    DicePursuit    = 'dice-pursuit',
}

export enum GameGenre {
    ARCADE   = 'ARCADE',
    SURVIVAL = 'SURVIVAL',
    ONE_TAP  = 'ONE-TAP',
    CLASSIC  = 'CLASSIC',
    PUZZLE   = 'PUZZLE',
    CASUAL   = 'CASUAL',
    WORD     = 'WORD',
}

export enum GameColor {
    NEON_BLUE = 'neon-blue',
    NEON_EMERALD = 'neon-emerald',
    NEON_PURPLE = 'neon-purple',
    NEON_PINK = 'neon-pink',
}

export interface GameEntry {
    slug: GameSlug
    id: string
    name: string
    desc: string
    genre: string
    color: GameColor
    component: Component
    controls: ControlLayout
}

export const games: GameEntry[] = [
    {
        slug: GameSlug.SpaceInvaders,
        id: 'SpaceInvaders',
        name: 'Space Invaders',
        desc: 'Shoot down the alien fleet before they reach Earth. Classic arcade action.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_BLUE,
        component: SpaceInvaders,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.AsteroidDodge,
        id: 'AsteroidDodge',
        name: 'Asteroid Dodge',
        desc: 'Pilot your ship through a relentless asteroid field. How long can you survive?',
        genre: GameGenre.SURVIVAL,
        color:GameColor.NEON_EMERALD,
        component: AsteroidDodge,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.FlappyRocket,
        id: 'FlappyRocket',
        name: 'Flappy Rocket',
        desc: "Boost your rocket through narrow gaps. One tap to fly — don't crash.",
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: FlappyRocket,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.CosmicBreakout,
        id: 'BreakoutGame',
        name: 'Cosmic Breakout',
        desc: 'Break every neon brick with a bouncing energy ball. Classic and satisfying.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: BreakoutGame,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.NeonSnake,
        id: 'SnakeGame',
        name: 'Neon Snake',
        desc: "Eat the glowing orbs and grow without hitting yourself. Speed builds up.",
        genre: GameGenre.CLASSIC,
        color:GameColor.NEON_EMERALD,
        component: SnakeGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.Game2048,
        id: 'Game2048',
        name: '2048',
        desc: 'Slide and merge tiles to reach 2048. Deceptively simple, endlessly deep.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: Game2048,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.PlanetMemory,
        id: 'MemoryMatch',
        name: 'Planet Memory',
        desc: 'Match all 8 planet pairs in the fewest flips. Test your space memory.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: MemoryMatch,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonTetris,
        id: 'NeonTetris',
        name: 'Neon Tetris',
        desc: 'Stack neon tetrominoes and clear lines before the stack reaches the top.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: NeonTetris,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.CosmicPong,
        id: 'CosmicPong',
        name: 'Cosmic Pong',
        desc: 'Face the CPU in a neon pong duel. First to 7 wins. Speed up or lose.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: CosmicPong,
        controls: ControlLayout.UpDown,
    },
    {
        slug: GameSlug.MeteorCatcher,
        id: 'MeteorCatcher',
        name: 'Meteor Catcher',
        desc: 'Tap the falling meteors before they hit the ground. How long can you last?',
        genre: GameGenre.CASUAL,
        color:GameColor.NEON_EMERALD,
        component: MeteorCatcher,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonRunner,
        id: 'NeonRunner',
        name: 'Neon Runner',
        desc: 'Dodge neon barriers in this endless side-scrolling runner — jump to survive.',
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_BLUE,
        component: NeonRunner,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.GravityFlip,
        id: 'GravityFlip',
        name: 'Gravity Flip',
        desc: 'Flip gravity to navigate a shifting sine-wave tunnel — how far can you go?',
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: GravityFlip,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.OrbitShield,
        id: 'OrbitShield',
        name: 'Orbit Shield',
        desc: 'Rotate a neon arc shield to deflect incoming meteors and protect your planet.',
        genre: GameGenre.ARCADE,
        color:GameColor.NEON_EMERALD,
        component: OrbitShield,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.StarCatcher,
        id: 'StarCatcher',
        name: 'Star Catcher',
        desc: 'Pilot a spaceship to catch falling stars while dodging pink energy bombs.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: StarCatcher,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.CosmicMinesweeper,
        id: 'CosmicMinesweeper',
        name: 'Cosmic Minesweeper',
        desc: 'Sweep a 9×9 minefield in deep space. Reveal cells, flag mines — clear the field without detonating.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: CosmicMinesweeper,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.TypeAttack,
        id: 'TypeAttack',
        name: 'Type Attack',
        desc: 'Space words fall from above — type them before they reach the danger line.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: TypeAttack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonWhack,
        id: 'NeonWhack',
        name: 'Neon Whack',
        desc: 'Whack glowing alien heads as they pop out of space-station ports. Click fast before they disappear.',
        genre: GameGenre.CASUAL,
        color:GameColor.NEON_EMERALD,
        component: NeonWhack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.LaserBounce,
        id: 'LaserBounce',
        name: 'Laser Bounce',
        desc: 'Aim your laser and ricochet shots off arena walls to destroy neon targets. Clear every target before shots run out.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: LaserBounce,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.WarpTunnel,
        id: 'WarpTunnel',
        name: 'Warp Tunnel',
        desc: 'Navigate a glowing ship through a pulsating wormhole. The tunnel tightens as you survive.',
        genre: GameGenre.SURVIVAL,
        color: GameColor.NEON_BLUE,
        component: WarpTunnel,
        controls: ControlLayout.UpDown,
    },
    {
        slug: GameSlug.ColorSurge,
        id: 'ColorSurge',
        name: 'Color Surge',
        desc: 'Shoot colored bubbles into the grid and pop matching clusters before they reach the danger line.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: ColorSurge,
        controls: ControlLayout.LrFire,
    },
    // ── New games ────────────────────────────────────────────────────────────
    {
        slug: GameSlug.Sudoku,
        id: 'SudokuGame',
        name: 'Sudoku',
        desc: 'Fill every row, column and 3×3 box with digits 1–9. Three difficulty levels with a built-in note mode.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: SudokuGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Nonogram,
        id: 'NonogramGame',
        name: 'Nonogram',
        desc: 'Decode the pixel art hidden inside an 8×8 grid using the number clues on each row and column.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: NonogramGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Sokoban,
        id: 'SokobanGame',
        name: 'Sokoban',
        desc: 'Push every crate onto the glowing goal squares across 5 hand-crafted warehouse levels.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_EMERALD,
        component: SokobanGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.SlidePuzzle,
        id: 'SlidePuzzle',
        name: 'Slide Puzzle',
        desc: 'Slide the 15 numbered tiles into order. Click tiles adjacent to the blank space to move them.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: SlidePuzzle,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Mastermind,
        id: 'MastermindGame',
        name: 'Mastermind',
        desc: 'Crack the hidden 4-color code in 10 attempts. Black pegs = right position, white = right color.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: MastermindGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.LightsOut,
        id: 'LightsOut',
        name: 'Lights Out',
        desc: 'Click cells to toggle them and their four neighbors. Turn every light off to win.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: LightsOut,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.FlowConnect,
        id: 'FlowConnect',
        name: 'Flow Connect',
        desc: 'Draw paths to connect each pair of colored dots. Fill every cell without crossing paths.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: FlowConnect,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Gomoku,
        id: 'GomokuGame',
        name: 'Gomoku',
        desc: 'Place stones on a 15×15 board. Get five in a row — horizontal, vertical or diagonal — to win.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_EMERALD,
        component: GomokuGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Wordle,
        id: 'WordleGame',
        name: 'Wordle',
        desc: 'Guess the secret 5-letter word in 6 tries. Green = correct spot, yellow = wrong position.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_EMERALD,
        component: WordleGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.WordSearch,
        id: 'WordSearch',
        name: 'Word Search',
        desc: 'Hunt for 8 hidden space words in a 10×10 letter grid. Drag to highlight words.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_BLUE,
        component: WordSearch,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.AnagramBlitz,
        id: 'AnagramBlitz',
        name: 'Anagram Blitz',
        desc: 'Unscramble as many words as you can in 60 seconds. +10 per correct answer, -1 to skip.',
        genre: GameGenre.WORD,
        color: GameColor.NEON_PINK,
        component: AnagramBlitz,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.PacMan,
        id: 'PacMan',
        name: 'Pac-Man',
        desc: 'Eat all the dots while avoiding ghosts. Grab a power pellet to turn the tables.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: PacMan,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.Frogger,
        id: 'FroggerGame',
        name: 'Frogger',
        desc: 'Guide your frog safely across busy roads and a fast-moving river to reach the lily pads.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_EMERALD,
        component: FroggerGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.MissileCommand,
        id: 'MissileCommand',
        name: 'Missile Command',
        desc: 'Click to launch interceptors and destroy incoming missiles before they obliterate your cities.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: MissileCommand,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Centipede,
        id: 'CentipedeGame',
        name: 'Centipede',
        desc: 'Blast the descending centipede before it reaches you. Beware wandering spiders.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: CentipedeGame,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.SimonSays,
        id: 'SimonSays',
        name: 'Simon Says',
        desc: 'Watch the color sequence flash, then repeat it. One mistake and it is game over.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_EMERALD,
        component: SimonSays,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.Checkers,
        id: 'CheckersGame',
        name: 'Checkers',
        desc: 'Classic draughts against a minimax AI. Capture all opponent pieces or block every move.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: CheckersGame,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.PianoTiles,
        id: 'PianoTiles',
        name: 'Piano Tiles',
        desc: 'Click the falling pink tiles before they pass the line. Miss three and the music stops.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: PianoTiles,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.ConnectFour,
        id: 'ConnectFour',
        name: 'Connect Four',
        desc: 'Drop discs to get four in a row against a minimax CPU. Horizontal, vertical or diagonal wins.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_PURPLE,
        component: ConnectFour,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.DicePursuit,
        id: 'DicePursuit',
        name: 'Dice Pursuit',
        desc: 'Roll 5 dice up to 3 times per turn and score across 13 Yahtzee-style categories.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PURPLE,
        component: DicePursuit,
        controls: ControlLayout.None,
    },
]

export const useGames = () => {
    const getGameBySlug = (slug: string) => games.find(game => game.slug === slug) ?? null
    return {games, getGameBySlug}
}
