import type {Component} from 'vue'
import {ControlLayout} from '~/types'
import {
    AsteroidDodge,
    BreakoutGame,
    ColorSurge,
    CosmicMinesweeper,
    CosmicPong,
    FlappyRocket,
    Game2048,
    GravityFlip,
    LaserBounce,
    MemoryMatch,
    MeteorCatcher,
    NeonRunner,
    NeonTetris,
    NeonWhack,
    OrbitShield,
    SnakeGame,
    SpaceInvaders,
    StarCatcher,
    TypeAttack,
    WarpTunnel,
} from '#components'

export enum GameSlug {
    SpaceInvaders = 'space-invaders',
    AsteroidDodge = 'asteroid-dodge',
    FlappyRocket = 'flappy-rocket',
    CosmicBreakout = 'cosmic-breakout',
    NeonSnake = 'neon-snake',
    Game2048 = '2048',
    PlanetMemory = 'planet-memory',
    NeonTetris = 'neon-tetris',
    CosmicPong = 'cosmic-pong',
    MeteorCatcher = 'meteor-catcher',
    NeonRunner = 'neon-runner',
    GravityFlip = 'gravity-flip',
    OrbitShield = 'orbit-shield',
    StarCatcher = 'star-catcher',
    CosmicMinesweeper = 'cosmic-minesweeper',
    TypeAttack = 'type-attack',
    NeonWhack = 'neon-whack',
    LaserBounce = 'laser-bounce',
    WarpTunnel = 'warp-tunnel',
    ColorSurge = 'color-surge',
}

export enum GameGenre {
    ARCADE = 'ARCADE',
    SURVIVAL = 'SURVIVAL',
    ONE_TAP = 'ONE-TAP',
    CLASSIC = 'CLASSIC',
    PUZZLE = 'PUZZLE',
    CASUAL = 'CASUAL',
}

export enum GameColor {
    NEON_BLUE = 'neon-blue',
    NEON_EMERALD = 'neon-emerald',
    NEON_PURPLE = 'neon-purple',
    NEON_PINK = 'neon-pink',
}

export interface GameEntry {
    slug: GameSlug
    id: string
    name: string
    desc: string
    genre: string
    color: GameColor
    component: Component
    controls: ControlLayout
}

export const games: GameEntry[] = [
    {
        slug: GameSlug.SpaceInvaders,
        id: 'SpaceInvaders',
        name: 'Space Invaders',
        desc: 'Shoot down the alien fleet before they reach Earth. Classic arcade action.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_BLUE,
        component: SpaceInvaders,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.AsteroidDodge,
        id: 'AsteroidDodge',
        name: 'Asteroid Dodge',
        desc: 'Pilot your ship through a relentless asteroid field. How long can you survive?',
        genre: GameGenre.SURVIVAL,
        color:GameColor.NEON_EMERALD,
        component: AsteroidDodge,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.FlappyRocket,
        id: 'FlappyRocket',
        name: 'Flappy Rocket',
        desc: "Boost your rocket through narrow gaps. One tap to fly — don't crash.",
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: FlappyRocket,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.CosmicBreakout,
        id: 'BreakoutGame',
        name: 'Cosmic Breakout',
        desc: 'Break every neon brick with a bouncing energy ball. Classic and satisfying.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: BreakoutGame,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.NeonSnake,
        id: 'SnakeGame',
        name: 'Neon Snake',
        desc: "Eat the glowing orbs and grow without hitting yourself. Speed builds up.",
        genre: GameGenre.CLASSIC,
        color:GameColor.NEON_EMERALD,
        component: SnakeGame,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.Game2048,
        id: 'Game2048',
        name: '2048',
        desc: 'Slide and merge tiles to reach 2048. Deceptively simple, endlessly deep.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: Game2048,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.PlanetMemory,
        id: 'MemoryMatch',
        name: 'Planet Memory',
        desc: 'Match all 8 planet pairs in the fewest flips. Test your space memory.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PURPLE,
        component: MemoryMatch,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonTetris,
        id: 'NeonTetris',
        name: 'Neon Tetris',
        desc: 'Stack neon tetrominoes and clear lines before the stack reaches the top.',
        genre: GameGenre.CLASSIC,
        color: GameColor.NEON_BLUE,
        component: NeonTetris,
        controls: ControlLayout.Dpad,
    },
    {
        slug: GameSlug.CosmicPong,
        id: 'CosmicPong',
        name: 'Cosmic Pong',
        desc: 'Face the CPU in a neon pong duel. First to 7 wins. Speed up or lose.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PINK,
        component: CosmicPong,
        controls: ControlLayout.UpDown,
    },
    {
        slug: GameSlug.MeteorCatcher,
        id: 'MeteorCatcher',
        name: 'Meteor Catcher',
        desc: 'Tap the falling meteors before they hit the ground. How long can you last?',
        genre: GameGenre.CASUAL,
        color:GameColor.NEON_EMERALD,
        component: MeteorCatcher,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonRunner,
        id: 'NeonRunner',
        name: 'Neon Runner',
        desc: 'Dodge neon barriers in this endless side-scrolling runner — jump to survive.',
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_BLUE,
        component: NeonRunner,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.GravityFlip,
        id: 'GravityFlip',
        name: 'Gravity Flip',
        desc: 'Flip gravity to navigate a shifting sine-wave tunnel — how far can you go?',
        genre: GameGenre.ONE_TAP,
        color: GameColor.NEON_PURPLE,
        component: GravityFlip,
        controls: ControlLayout.Tap,
    },
    {
        slug: GameSlug.OrbitShield,
        id: 'OrbitShield',
        name: 'Orbit Shield',
        desc: 'Rotate a neon arc shield to deflect incoming meteors and protect your planet.',
        genre: GameGenre.ARCADE,
        color:GameColor.NEON_EMERALD,
        component: OrbitShield,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.StarCatcher,
        id: 'StarCatcher',
        name: 'Star Catcher',
        desc: 'Pilot a spaceship to catch falling stars while dodging pink energy bombs.',
        genre: GameGenre.CASUAL,
        color: GameColor.NEON_PINK,
        component: StarCatcher,
        controls: ControlLayout.Lr,
    },
    {
        slug: GameSlug.CosmicMinesweeper,
        id: 'CosmicMinesweeper',
        name: 'Cosmic Minesweeper',
        desc: 'Sweep a 9×9 minefield in deep space. Reveal cells, flag mines — clear the field without detonating.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_BLUE,
        component: CosmicMinesweeper,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.TypeAttack,
        id: 'TypeAttack',
        name: 'Type Attack',
        desc: 'Space words fall from above — type them before they reach the danger line.',
        genre: GameGenre.ARCADE,
        color: GameColor.NEON_PURPLE,
        component: TypeAttack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.NeonWhack,
        id: 'NeonWhack',
        name: 'Neon Whack',
        desc: 'Whack glowing alien heads as they pop out of space-station ports. Click fast before they disappear.',
        genre: GameGenre.CASUAL,
        color:GameColor.NEON_EMERALD,
        component: NeonWhack,
        controls: ControlLayout.None,
    },
    {
        slug: GameSlug.LaserBounce,
        id: 'LaserBounce',
        name: 'Laser Bounce',
        desc: 'Aim your laser and ricochet shots off arena walls to destroy neon targets. Clear every target before shots run out.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: LaserBounce,
        controls: ControlLayout.LrFire,
    },
    {
        slug: GameSlug.WarpTunnel,
        id: 'WarpTunnel',
        name: 'Warp Tunnel',
        desc: 'Navigate a glowing ship through a pulsating wormhole. The tunnel tightens as you survive.',
        genre: GameGenre.SURVIVAL,
        color: GameColor.NEON_BLUE,
        component: WarpTunnel,
        controls: ControlLayout.UpDown,
    },
    {
        slug: GameSlug.ColorSurge,
        id: 'ColorSurge',
        name: 'Color Surge',
        desc: 'Shoot colored bubbles into the grid and pop matching clusters before they reach the danger line.',
        genre: GameGenre.PUZZLE,
        color: GameColor.NEON_PINK,
        component: ColorSurge,
        controls: ControlLayout.LrFire,
    },
]

export const useGames = () => {
    const getGameBySlug = (slug: string) => games.find(game => game.slug === slug) ?? null
    return {games, getGameBySlug}
}
